Character.create(name: "Greg the Old", strength: 14, dexterity: 12, consitution:12, intelligence: 11, wisdom: 16, charisma: 13, char_race_id: 12, char_class_id: 1)
Character.create(name: "Lucinda Hogwild", strength: 11, dexterity: 13, consitution:12, intelligence: 16, wisdom: 14, charisma: 14, char_race_id: 7, char_class_id: 12)

Monster.create(name: "Gerblin", description: "A short, green creature. Looks like Common and sounds like Kelsey Grammar.", hit_points: 10)
Monster.create(name: "Eldritch ginuea pig", description: "An incombrehensible horror often eaten as a snack in Peru.", hit_points: 50)

CharClass.create(name: "Barbarian", description: "A fierce warrior of primitive background who can enter a battle rage.")
CharClass.create(name: "Bard", description: "An inspiring magician whose music echoes the power of creation.")
CharClass.create(name: "Cleric", description: "A priestly champion who wields divine magic in service of a higher power.")
CharClass.create(name: "Druid", description: "A priest of the Old Faith who wields the powers of nature and adopts animal forms.")
CharClass.create(name: "Fighter", description: "A master of martial combat who is skilled with a variety of weapons and armor.")
CharClass.create(name: "Monk", description: "A master of martial arts who harnesses the power of the body in pursuit of physical and spiritual perfection.")
CharClass.create(name: "Paladin", description: "A holy warrior who is bound to their deity through a sacred oath.")
CharClass.create(name: "Ranger", description: "A warrior who combats threats on the edges of civilization and defends nature.")
CharClass.create(name: "Rogue", description: "A scoundrel who uses stealth and trickery to overcome obstacles and enemies.")
CharClass.create(name: "Sorcerer", description: "A spellcaster who possesses innate magic due to their bloodline or a magical gift.")
CharClass.create(name: "Warlock", description: "A wielder of eldritch magic whose powers are derived from a bargain with an extraplanar entity.")
CharClass.create(name: "Wizard", description: "A scholarly magic-user capable of manipulating the structures of reality.")

CharRace.create(name: "Aarakocra", description: "Sequestered in high mountains atop tall trees, the aarakocra, sometimes called birdfolk, evoke fear and wonder.")
CharRace.create(name: "Aasimar", description: "Aasimar are placed in the world to serve as guardians of law and good. Their patrons expect them to strike at evil, lead by example, and further the cause of justice.")
CharRace.create(name: "Dragonborn", description: "Dragonborn look very much like dragons standing erect in humanoid form, though they lack wings or a tail.")
CharRace.create(name: "Dwarf", description: "Bold and hardy, dwarves are known as skilled warriors, miners, and workers of stone and metal.")
CharRace.create(name: "Elf", description: "Elves are a magical people of otherworldly grace, living in the world but not entirely part of it.")
CharRace.create(name: "Genasi", description: "Genasi carry the power of the elemental planes of air, earth, fire, and water in their blood.")
CharRace.create(name: "Gnome", description: "A gnome’s energy and enthusiasm for living shines through every inch of his or her tiny body.")
CharRace.create(name: "Goliath", description: "Strong and reclusive, every day brings a new challenge to a goliath.")
CharRace.create(name: "Half-Elf", description: "Half-elves combine what some say are the best qualities of their elf and human parents.")
CharRace.create(name: "Halfling", description: "The diminutive halflings survive in a world full of larger creatures by avoiding notice or, barring that, avoiding offense.")
CharRace.create(name: "Half-Orc", description: "Half-orcs’ grayish pigmentation, sloping foreheads, jutting jaws, prominent teeth, and towering builds make their orcish heritage plain for all to see.")
CharRace.create(name: "Human", description: "Humans are the most adaptable and ambitious people among the common races. Whatever drives them, humans are the innovators, the achievers, and the pioneers of the worlds.")
CharRace.create(name: "Tiefling", description: "To be greeted with stares and whispers, to suffer violence and insult on the street, to see mistrust and fear in every eye: this is the lot of the tiefling.")
